src/main/resources/assets/quark/materials/hardened_clay_tiles.json, src/main/resources/assets/quark/materials/minecraft_end_bricks.json, src/main/resources/assets/quark/materials/minecraft_prismarine_bricks.json, src/main/resources/assets/quark/materials/minecraft_prismarine_dark.json, src/main/resources/assets/quark/materials/minecraft_prismarine_rough.json, src/main/resources/assets/quark/materials/minecraft_stone.json, src/main/resources/assets/quark/materials/minecraft_stone_andesite.json, src/main/resources/assets/quark/materials/minecraft_stone_diorite.json, src/main/resources/assets/quark/materials/minecraft_stone_granite.json, src/main/resources/assets/quark/materials/reed_block.json, src/main/resources/assets/quark/materials/sandy_bricks.json, src/main/resources/assets/quark/materials/stained_clay_tiles.json, src/main/resources/assets/quark/materials/stone_andesite_bricks.json, src/main/resources/assets/quark/materials/stone_basalt.json, src/main/resources/assets/quark/materials/stone_basalt_bricks.json, src/main/resources/assets/quark/materials/stone_basalt_polished.json, src/main/resources/assets/quark/materials/stone_diorite_bricks.json, src/main/resources/assets/quark/materials/stone_granite_bricks.json, src/main/resources/assets/quark/materials/thatch.json
Would you rather have the compat in your mod or mine?
=> Add materials for BuildingBricks compat

src/main/java/vazkii/quark/decoration/block/BlockCustomChest.java
=> fixed chest rotation when placed in certain ways

src/main/java/vazkii/quark/tweaks/QuarkTweaks.java, src/main/java/vazkii/quark/tweaks/feature/DoubleDoors.java
- Added new tweaks feature Double Door, which is a pretty much a copy and paste of the one in charset,  except fitted to Quark. Unlike, Charset double doors this one can work with modded doors.
=> Added new tweaks feature Double Doors

src/main/java/vazkii/quark/management/client/gui/GuiButtonChest.java
- Changed Array import from the scala Array to the java Array. Fixes #211.
=> Wrong Array Import

src/main/resources/assets/quark/loot_tables/chests/pirate_chest.json
The amount of resources obtained from these ships was just ridiculous way over the top bonkers. The rebalanced loot tables will give much less overall. Hopefully satisfaction is still high enough that the ships are worth exploring.
=> Rebalanced pirate ship loot - hard nerf

src/main/java/vazkii/quark/world/QuarkWorld.java, src/main/java/vazkii/quark/world/feature/SpongeDriesInNether.java
First suggested here: https://www.reddit.com/r/minecraftsuggestions/comments/5l12cu/putting_a_wet_sponge_in_the_nether_dries_it/
=> Wet sponge now dries in Nether

src/main/java/vazkii/quark/automation/feature/PistonsMoveTEs.java
Trying to push one turns the game into a very pretty lightshow that changes colors when you move your mouse
https://gyazo.com/f4e9ccf59a1a411db611466c6ce1db23
=> Blacklist botania:starfield from rendering in move

src/main/resources/assets/quark/models/block/overrides/piston_head_normal.json, src/main/resources/assets/quark/models/block/overrides/piston_head_sticky.json
1 texture on both normal and sticky piston was rotated incorrectly so I fixed it.
btw I'm new to Github
=> PE pistons model fix

src/main/java/vazkii/quark/building/feature/WorldStoneBricks.java, src/main/java/vazkii/quark/world/feature/RevampStoneGen.java
welp another go, also found a typo in the limestone integration..
=> Fixed Chisel Integration

src/main/java/vazkii/quark/base/network/message/MessageDropoff.java, src/main/java/vazkii/quark/base/network/message/MessageRestock.java
- Changed MessageDropoff and MessageRestock to create  and add a scheduled task that calls droppoff and restock, fixes #900.
=> Changed DropoffHandler to use scheduled task, fixes #900.

src/main/java/vazkii/quark/tweaks/feature/MinecartInteraction.java
- Remove the hardcoded references to the minecarts class and used the ForgeRegistries.ENTITIES to find the EntityEntry. Fixes #895.
- Add a null check to the code in case the map returns a null entitiy.
=> Fixed MinecartInteraction with substituted carts, fixes #895.

src/main/java/vazkii/quark/client/feature/ChestSearchBar.java
=> Fix #924 by skipping invalid enchantment IDs on books

src/main/java/vazkii/quark/misc/feature/EndermitesIntoShulkers.java, web/features.json
https://minecraft.curseforge.com/projects/mite2shulker
=> Mark Endermites into Shulkers as overlapping with Mite2Shulker

build.gradle
Yet another port of Vazkii/Patchouli#2, and replaces the deobf jar with a source jar and an api jar.
=> Clean up buildscript, source + api jars

Jenkinsfile, build.gradle
Basically the same thing as Vazkii/Patchouli@7c54c6ec360211293d84e2ef4846a8d250101f9, will need Jared to set it up on his side though.
@jaredlll08 please check if it's all correct?
(crosslinking the Psi version for convenience: Vazkii/Psi#483)
=> An attempt at maven

src/main/resources/assets/quark/lang/ru_ru.json
- Some fixes
- New features localized
=> Updated ru_ru.json

src/main/resources/data/quark/recipes/tweaks/crafting/utility/coral/bubble_to_magenta.json
https://discordapp.com/channels/154261184701267969/615706272033013790/693231360885915668
Requested by five
Just to be a bit more accurate and work better with Upgrade Aquatic if possible
=> Changing Bubble Coral to output Magenta Dye

src/main/resources/assets/quark/models/block/candle.json, src/main/resources/assets/quark/models/block/chute.json, src/main/resources/assets/quark/models/block/inductor.json, src/main/resources/assets/quark/models/block/inductor_locked.json, src/main/resources/assets/quark/models/block/iron_rod.json, src/main/resources/assets/quark/models/block/iron_rod_base.json, src/main/resources/assets/quark/models/block/paper_lantern.json, src/main/resources/assets/quark/models/block/randomizer_off.json, src/main/resources/assets/quark/models/block/randomizer_on_left.json, src/main/resources/assets/quark/models/block/randomizer_on_right.json
Fixes #2006, should probably reopen #1990 as it's separate
=> Remove several unneccesary faces and add cullface

src/main/resources/assets/quark/models/block/rope.json
another minor one i'd missed, nothing much
=> Add cullface to ropes

web/features.json
Digusting spelling error. This is exactly the kind of errors I come to expect from such a disgutsingly ill-made mod. I graduated with an A+ in English all of my elemnetary to middle school classes and my sister is the third best speller in the United State of America. Yuo should be ashamed of yourself and stop making mods forever. In fact, do that, doin't even pull this request. Come on, I double dog dare dare you. Don't you dare pull this request you ugly pig with a face like a smeely lump of food I had to pull out of the garbage disposal after my girlfreind told me this wasn't working. With my bare hands. It was digsusting. Just like your spelling you idiot. Don't ever interact with me or my pull requests ever again you lard head.
In fact I am so disgusted by your antiliteracy i am …
=> Literally unplayable speling error

src/main/resources/assets/quark/lang/es_ar.json, src/main/resources/assets/quark/lang/es_es.json, src/main/resources/assets/quark/lang/es_mx.json
=> Update spanish translations

src/main/resources/assets/quark/models/block/vertical_slab.json, src/main/resources/assets/quark/models/block/vertical_slab_tinted.json
Vertical Slabs have some weird model issues on the east and bottom side, this is fixed as shown in the image
=> Fix vertical slab model visual issues

src/main/resources/data/minecraft/tags/blocks/impermeable.json, src/main/resources/data/minecraft/tags/blocks/soul_fire_base_blocks.json, src/main/resources/data/minecraft/tags/blocks/soul_speed_blocks.json, src/main/resources/data/quark/tags/blocks/crystal.json
- Added Dirty Glass and Framed Glass to #impermeable so that water and lava don't drip through, to be consistent with other glass panes
- Added Soul Sandstone blocks to #soul_speed_blocks so they can affect Soul Speed
- Added Soul Sandstone blocks to #soul_fire_base_blocks so you can put Soul Fire on them
=> Update some tags

src/main/java/vazkii/quark/base/mixin/TemplateMixin.java
=> Fix TemplateMixin.java

src/main/java/vazkii/quark/base/proxy/ClientProxy.java
Yeah, it's this simple. Probably wont see much use because barely any mod has this working, but it is a thing.
=> Make Quark's config button in the mod list work

src/main/java/vazkii/quark/automation/module/DispensersPlaceBlocksModule.java, src/main/java/vazkii/quark/base/handler/FuelHandler.java, src/main/java/vazkii/quark/base/handler/MiscUtil.java, src/main/java/vazkii/quark/base/handler/SortingHandler.java, src/main/java/vazkii/quark/base/proxy/CommonProxy.java, src/main/java/vazkii/quark/base/recipe/ExclusionRecipe.java, src/main/java/vazkii/quark/base/recipe/PotionIngredient.java, src/main/java/vazkii/quark/building/module/VariantChestsModule.java, src/main/java/vazkii/quark/client/module/GreenerGrassModule.java, src/main/java/vazkii/quark/client/tooltip/EnchantedBookTooltips.java, src/main/java/vazkii/quark/experimental/module/CustomUndergroundBiomeModule.java, src/main/java/vazkii/quark/oddities/container/EnchantmentMatrix.java, src/main/java/vazkii/quark/oddities/magnetsystem/MagnetSystem.java, src/main/java/vazkii/quark/oddities/module/MatrixEnchantingModule.java, src/main/java/vazkii/quark/tools/item/AncientTomeItem.java, src/main/java/vazkii/quark/tools/module/AncientTomesModule.java, src/main/java/vazkii/quark/world/module/BigStoneClustersModule.java, src/main/java/vazkii/quark/world/module/FairyRingsModule.java, src/main/java/vazkii/quark/world/module/NewStoneTypesModule.java
Moves everything except registering recipe serializers and one biome call to vanilla registry calls.
=> move (most) things to regular registry calls

src/main/java/vazkii/quark/oddities/client/screen/BackpackInventoryScreen.java
There you go, set up my fork. Closes #2681
=> BackpackInventoryScreen support multiple image buttons

src/main/java/vazkii/quark/content/building/module/VariantChestsModule.java
adds support for cobbler, conjurer, dungeoncrawl, dungeons plus, i/f, pandoras creatures, and valhesia structures
=> Add variant chest config support for structures from other mods

src/main/resources/assets/quark/lang/es_ar.json, src/main/resources/assets/quark/lang/es_es.json, src/main/resources/assets/quark/lang/es_mx.json
Autowalk, realistic large biomes, fix format
=> Update es_es.json, es_mx.json, es_ar.json

src/main/java/vazkii/quark/content/client/module/GreenerGrassModule.java
* remove Duckweed as it isn't colored dynamically
* add all dynamically colored Abnormals leaves
=> Add Abnormals compatibility to Greener Grass module

src/main/java/vazkii/quark/content/management/module/ItemSharingModule.java, src/main/java/vazkii/quark/mixin/client/ItemRendererMixin.java, src/main/resources/META-INF/accesstransformer.cfg
=> Repair item sharing at last w00t

src/main/java/vazkii/quark/base/block/QuarkVineBlock.java, src/main/java/vazkii/quark/base/handler/GeneralConfig.java, src/main/java/vazkii/quark/content/building/block/GrateBlock.java, src/main/java/vazkii/quark/content/client/module/AutoWalkKeybindModule.java, src/main/java/vazkii/quark/content/tweaks/module/DirtToPathModule.java, src/main/java/vazkii/quark/content/world/module/BlossomTreesModule.java
=> Misc. cleanup of some issues

src/main/java/vazkii/quark/content/building/module/CompressedBlocksModule.java, src/main/java/vazkii/quark/content/building/module/LeafCarpetModule.java
See https://github.com/Vazkii/Quark/issues/2823#issuecomment-754989614
=> Fix composter concurrency issue

build.gradle, src/main/java/vazkii/quark/addons/oddities/container/EnchantmentMatrix.java, src/main/java/vazkii/quark/addons/oddities/item/BackpackItem.java, src/main/java/vazkii/quark/base/client/config/gui/CategoryScreen.java, src/main/java/vazkii/quark/base/client/config/gui/widget/ConfigElementList.java, src/main/java/vazkii/quark/base/handler/OverrideRegistryHandler.java, src/main/java/vazkii/quark/base/handler/SimilarBlockTypeHandler.java, src/main/java/vazkii/quark/base/handler/SortingHandler.java, src/main/java/vazkii/quark/base/recipe/ExclusionRecipe.java, src/main/java/vazkii/quark/base/util/PotionReflection.java, src/main/java/vazkii/quark/content/automation/block/RedstoneInductorBlock.java, src/main/java/vazkii/quark/content/automation/block/RedstoneRandomizerBlock.java, src/main/java/vazkii/quark/content/automation/client/render/ChainRenderer.java, src/main/java/vazkii/quark/content/management/module/ItemSharingModule.java, src/main/java/vazkii/quark/content/mobs/client/model/ToretoiseModel.java, src/main/java/vazkii/quark/content/tweaks/client/item/CompassAngleGetter.java, src/main/java/vazkii/quark/content/tweaks/module/LockRotationModule.java, src/main/java/vazkii/quark/content/tweaks/module/ReacharoundPlacingModule.java, src/main/java/vazkii/quark/mixin/client/EntityRendererManagerMixin.java
=> Fix all build warnings

build.gradle, runClient.launch, runServer.launch, spotless/eclipse.importorder, spotless/eclipseformat.xml, spotless/pmd-ruleset.xml, src/main/java/vazkii/quark/addons/oddities/client/render/MagnetizedBlockTileEntityRenderer.java, src/main/java/vazkii/quark/addons/oddities/item/BackpackItem.java, src/main/java/vazkii/quark/base/client/config/gui/AbstractScrollingWidgetScreen.java, src/main/java/vazkii/quark/base/client/config/gui/widget/ConfigElementList.java, src/main/java/vazkii/quark/base/client/render/GenericChestTERenderer.java, src/main/java/vazkii/quark/base/handler/ContributorRewardHandler.java, src/main/java/vazkii/quark/base/util/WeightedSelector.java, src/main/java/vazkii/quark/content/building/block/VariantChestBlock.java, src/main/java/vazkii/quark/content/building/tile/VariantTrappedChestTileEntity.java, src/main/java/vazkii/quark/content/mobs/client/layer/StonelingItemLayer.java, src/main/java/vazkii/quark/content/mobs/client/model/CrabModel.java, src/main/java/vazkii/quark/content/mobs/entity/FoxhoundEntity.java, src/main/java/vazkii/quark/content/tools/module/SeedPouchModule.java, src/main/java/vazkii/quark/content/tweaks/ai/WantLoveGoal.java, src/main/java/vazkii/quark/content/world/block/ChorusVegetationBlock.java, src/main/java/vazkii/quark/content/world/block/SpeleothemBlock.java, src/main/java/vazkii/quark/mixin/PistonBlockMixin.java
Spotless is installed too; please configure to taste and run `gradlew spotlessApply` to create a gigantic diff hahayes
=> Add PMD, clean up warnings

src/main/resources/assets/quark/models/block/vertical_planks.json
This has bugged me ever since I found out the model bug existed, finally decided I was gonna fix it today.
=> Fix model for vertical planks

src/main/resources/assets/quark/models/block/vertical_planks.json
This time, I made it match better with regular planks.
=> Fix more vertical plank jank

src/main/java/vazkii/quark/base/handler/GeneralConfig.java
Fixes another extract/insert dupe.
=> Add Refined Storage FilterScreen to ignoredScreens

src/main/java/vazkii/quark/content/management/module/ItemSharingModule.java, src/main/resources/META-INF/accesstransformer.cfg
=> Fix the weird rendering for item sharing

src/main/java/vazkii/quark/content/automation/module/ChainLinkageModule.java
This pull request adds new dispense behavior for chains.
Allowing dispensers to link two minecarts in front of them together.
This wasn't possible to automate before, since chain linking could only be done by the player.
Ability to do this comes in handy when building an automated train station.
=> Allow chain linking minecarts using a dispenser

src/main/java/vazkii/quark/base/handler/InventoryTransferHandler.java
Fixes restocking player's inventory from inventories that support more than maxstacksize stack sizes.
=> Oversized stacks restock fix

src/main/java/vazkii/quark/content/client/module/GreenerGrassModule.java
Adds the Valhelsia Structures grass block to the block list in the Greener Grass Module.
=> Add valhelsia grass block to Greener Grass Module

src/main/java/vazkii/quark/content/mobs/entity/ToretoiseEntity.java, src/main/java/vazkii/quark/content/mobs/module/ToretoiseModule.java
I really like the toretoises. I mostly want this change because the current version has a bug that effectively makes toretoise cooldown zero, so if you can find one of them and make a cave root farm you get unlimited ores too easily. Also added config options for a modpack I'm working on.
=> Changes to toretoises

src/main/java/vazkii/quark/content/building/block/GrateBlock.java, src/main/java/vazkii/quark/content/mobs/entity/FrogEntity.java, src/main/java/vazkii/quark/content/world/block/CaveCrystalClusterBlock.java
3 Bugfixes to #3144, #3073 and #2487.
Also a change to Corundum Clusters to bring them more in line with Amethyst Clusters from 1.17.
(Hopefully this isn't too awful)
=> A few bugfixes.

src/main/resources/assets/quark/lang/es_ar.json, src/main/resources/assets/quark/lang/es_es.json, src/main/resources/assets/quark/lang/es_mx.json
* Rename Tedium to Endermosh
* Fix translation for dusky myalite
=> Update spanish translations (es - ar, es, mx)

Jenkinsfile
```
sudo du -ha . | sort -r -h | head -n 20
47G     .
13G     ./Quark/branches
13G     ./Quark
8.8G    ./Quark/branches/master/builds
8.8G    ./Quark/branches/master
```
=> Please give me my 13G back

src/main/java/vazkii/quark/addons/oddities/block/be/PipeBlockEntity.java, src/main/java/vazkii/quark/addons/oddities/inventory/CrateMenu.java, src/main/java/vazkii/quark/base/handler/MiscUtil.java
This adds support for WorldyContainerHolders to Pipes, allowing them to interact with Composters (for example).
=> Added support for WordlyContainerHolders to Pipes

src/main/java/vazkii/quark/base/handler/FuelHandler.java, src/main/java/vazkii/quark/content/building/block/WeatheringCopperVerticalSlabBlock.java, src/main/resources/data/quark/loot_tables/blocks/crimson_bookshelf.json, src/main/resources/data/quark/loot_tables/blocks/warped_bookshelf.json
defaultBlockState -> withPropertiesOf
=> Fix #3555, #3550, #3549

src/main/java/vazkii/quark/content/tweaks/module/HoeHarvestingModule.java, src/main/java/vazkii/quark/content/tweaks/module/SimpleHarvestModule.java
- Added `boolean isHoe(ItemStack stack)` helper function
- Implemented function internally within the Class where the condition was hardcoded
- Refactored hardcoded `isHoe` conditions to instead call the new helper function
- Performance improvement of `void harvestAndReplant(Level world, BlockPos pos, BlockState inWorld, Player player)` to return as early as possible if not called Server Side
- Modified `boolean click(Player player, BlockPos pos)` to store harvests in a `boolean` rather than `int32` to reduce field width
=> [Refactor] SimpleHarvestModule.java + HoeHarvestingModule.java

src/main/java/vazkii/quark/base/handler/GeneralConfig.java
This will fix MarkusBordihn/BOs-Daily-Rewards#4
=> [Main] Add Daily Rewards RewardScreen to ignoredScreens

src/main/resources/assets/quark/lang/en_us.json
Adds missing lang entries for potted chorus weeds and potted chorus twist
=> Add missing potted plant lang entries

src/main/java/vazkii/quark/content/tweaks/client/layer/ArmorStandFakePlayerLayer.java
=> Fix small armor stands not rendering player model properly

src/main/java/vazkii/quark/content/building/block/HollowLogBlock.java, src/main/java/vazkii/quark/content/building/block/HollowPillarBlock.java
Only skylight for now, working on general lighting
Edit: Done, got some questions in process (in comments)
=> Make hollow logs block light when placed horizontally

src/main/java/vazkii/quark/content/management/module/AutomaticToolRestockModule.java
Fixes #4119
- Adds a configurable list of items the restock feature should ignore when doing the swapping.
- By default the list contains the Botania rods that get swapped incorrectly by this feature.
=> Add item blacklist for the auto tool restock feature

src/main/java/vazkii/quark/base/handler/MiscUtil.java
It isnt used in the mod anymore, and anything it could reasonably be used for can be done thru mixin to my knowledge
=> Remove editFinalField from MiscUtil

src/main/java/vazkii/quark/base/handler/MiscUtil.java, src/main/java/vazkii/quark/content/mobs/entity/Crab.java, src/main/resources/data/quark/tags/items/crab_tempt_items.json
Probably better just to do the merging in one tag than in code. Also has the benefit of allowing players to use a custom item that isnt a fish if they REALLY wanted to
=> Crab Temptation Items as one tag

src/main/java/org/violetmoon/quark/base/client/render/QuarkBoatRenderer.java, src/main/java/org/violetmoon/quark/content/automation/module/JukeboxAutomationModule.java, src/main/java/org/violetmoon/quark/content/building/client/render/be/VariantChestRenderer.java, src/main/java/org/violetmoon/quark/content/building/module/VariantChestsModule.java, src/main/java/org/violetmoon/quark/content/management/module/ItemSharingModule.java, src/main/java/org/violetmoon/quark/content/tweaks/client/emote/CustomEmoteDescriptor.java, src/main/java/org/violetmoon/quark/content/tweaks/client/emote/CustomEmoteIconResourcePack.java, src/main/java/org/violetmoon/quark/content/tweaks/module/EmotesModule.java, src/main/java/org/violetmoon/quark/content/world/module/GlimmeringWealdModule.java, src/main/java/org/violetmoon/quark/integration/lootr/ILootrIntegration.java, src/main/java/org/violetmoon/quark/integration/lootr/LootrIntegration.java, src/main/java/org/violetmoon/quark/integration/lootr/client/LootrVariantChestRenderer.java, src/main/java/org/violetmoon/quark/mixin/PlayerAdvancementsMixin.java, src/main/java/org/violetmoon/zeta/advancement/modifier/WaxModifier.java, src/main/resources/META-INF/accesstransformer.cfg, src/main/resources/assets/quark/atlases/variant_chest.json
=> Zeta 1.20 minor porting (#4)

src/main/java/org/violetmoon/quark/base/world/WorldGenHandler.java, src/main/java/org/violetmoon/quark/content/world/module/GlimmeringWealdModule.java, src/main/java/org/violetmoon/quark/integration/terrablender/TerraBlenderIntegration.java, src/main/java/org/violetmoon/quark/mixin/DamageSourcesMixin.java, src/main/java/org/violetmoon/quark/mixin/PlayerAdvancementsMixin.java, src/main/java/org/violetmoon/quark/mixin/PotionUtilsMixin.java, src/main/java/org/violetmoon/quark/mixin/ServerEntityMixin.java, src/main/resources/META-INF/accesstransformer.cfg
I GOT IT TO GET INTO A WORLD LETS GOOOO
=> Worlds not too beyond our former imaginations (Zeta Porting #5)

src/main/java/org/violetmoon/quark/content/tools/item/PickarangItem.java, src/main/java/org/violetmoon/quark/content/tweaks/client/screen/widgets/TranslucentButton.java
Minor fixes for some of Zeta
Now the hard stuff must be conquered
=> The "Black Box ~ Void Incarnate" has gone on break

src/main/java/org/violetmoon/quark/base/handler/InventoryTransferHandler.java
=> Prevents extracting item with the extract button from containers that can "lock" their slots

src/main/java/org/violetmoon/quark/addons/oddities/entity/TotemOfHoldingEntity.java, src/main/java/org/violetmoon/quark/addons/oddities/module/TotemOfHoldingModule.java, src/main/java/org/violetmoon/quark/base/config/QuarkGeneralConfig.java, src/main/java/org/violetmoon/quark/content/tweaks/compat/TotemOfHoldingCuriosCompat.java
Makes Totem of holding equip the curios you had before dying, like it does for armor
Also fixes the sort button not showing in the curios screen
#4622
=> Add curios compat to the totem of holding

src/main/java/org/violetmoon/quark/base/handler/InventoryTransferHandler.java
Creative inventory is client side only duh
=> Makes transfer buttons work on servers (oops my bad). Closes #4653

src/main/resources/data/minecraft/tags/items/bookshelf_books.json
=> Added ability to put Ancient Tomes in Chiseled Bookshelves

src/main/java/org/violetmoon/quark/content/client/module/GreenerGrassModule.java
https://www.curseforge.com/minecraft/mc-mods/grass-slabs-carpets-stairs
Fixes https://github.com/tinytransfem/Grass_Slabs/issues/16.
=> Add support for "Grass Slabs, Carpets & Stairs" to greener grass module.
