VazkiiMods/Quark

- src/main/java/vazkii/quark/tweaks/QuarkTweaks.java
- src/main/java/vazkii/quark/tweaks/feature/SheepArmor.java
Hey, not sure if you are open to feature PRs but after showing this feature off I received a bunch of requests to PR it into Quark. The feature is actually really basic, when a sheep has wool it has one point of armor, and if it has been sheared it doesn't. This may seem like a trivial addition however I feel it does a great deal to flesh out sheep. It also means that sheep wont take as much damage from wolves or stray arrows / creeper blasts. 
This works by adding a +1 armor attribute to sheep when they have wool, and removing it when they have been sheared. This is handled in a similar way by vanilla potions. The UUID is a V4 ID generated by [this](https://www.uuidgenerator.net/) site. 
I tested and confirmed that this feature is working by using the armor point module in WAWLA.
> Gave sheep armor for their wool.

- README.md
- build.gradle
Forge 1.9.4 requires ForgeGradle 2.2, and will crash when decompiling MC without it, like when running `setupDecompWorkspace` for the first time.
> Update ForgeGradle and set coreMod in build.gradle

- src/main/java/vazkii/quark/world/feature/Wraiths.java
This will allow the Wraith to spawn in my [mod](https://minecraft.curseforge.com/projects/netherex). And fix this issue LogicTechCorp/NetherEx#7
> Fix for Wraiths not spawning in overridden Nether

- src/main/java/vazkii/quark/management/feature/FavoriteItems.java
- Added a reflection to get the value of GuiContainer.guiLeft & GuiContainer.guiTop, this being a little  hacky, allows for the correct lock position with other modded chest containers with different sized xSize and ySize.
- Fixes #213
> Fixed display bug with favorite icon in gui with different sizes

- src/main/java/vazkii/quark/world/feature/AncientTomes.java
- src/main/java/vazkii/quark/world/feature/BuriedTreasure.java
**What does this PR do?**
This PR allows Quark's LootFunctions to be serialised and deserialised.
**Why is this PR necessary?**
I make the mod [LootTweaker](https://github.com/Leviathan143/LootTweaker). LootTweaker has a command that dumps loot tables to files by serialising them. One of my users reported that having Quark installed caused a non-fatal error when this command was used. This error is caused by Quark's LootFunctions being unserialisable. While vanilla does not serialise loot tables as far as I am aware, other mods(like LootTweaker) may wish to. Additionally vanilla is capable of serialising loot tables, so I suspect it may do so in a future update.
This PR will also allow Quark's LootFunctions to be used in loot tables by users, as it makes the LootFunctions deserialisable. …
> Create and register serialisers for Quark's LootFunctions

- src/main/java/vazkii/quark/decoration/entity/EntityColoredItemFrame.java
When a colored item frame is on a block, and the block is broken, then the item frame drops, but not the item in it. This PR fixes that problem.
> Drop items in frame when backing block breaks

- src/main/java/vazkii/quark/misc/feature/AncientTomes.java
#347 was caused by a enchanted book whose enchantments, when gotten using the EnchantmentHelper, had a null somewhere. It appears to happen when there is an enchantment on the book that is not in the enchantment registry.
> Fix crash on invalid enchanted book

- README.md
There is now an official Github repo for the Java Universal Tween Engine.
> Update link to the Java UTE to Github

- src/main/java/vazkii/quark/automation/feature/PistonsMoveTEs.java
Integrated Dynamics doesn't support moving cables and will crash if you try (CyclopsMC/IntegratedDynamics#309), so we shouldn't allow it.
> Blacklist moving integrateddynamics:cable with pistons

- src/main/java/vazkii/quark/misc/feature/AncientTomes.java
Fixes misbehaviour of ancient tomes when the target book has more than one enchantment, see screenshots.
Also handles tomes with multiple enchantments gracefully (those can be obtained using commands).
---
Before: ![2017-10-19_22 43 27](https://user-images.githubusercontent.com/10252708/31793257-0a18bf6a-b51f-11e7-8ccb-ac5784371e20.png)
After: ![2017-10-19_22 42 00](https://user-images.githubusercontent.com/10252708/31793282-1a03d7c0-b51f-11e7-84e2-3edd793eb6e4.png)
---
Before:![2017-10-19_22 43 34](https://user-images.githubusercontent.com/10252708/31793295-2124fd22-b51f-11e7-87de-6a456b5a1988.png)
After: ![2017-10-19_22 41 52](https://user-images.githubusercontent.com/10252708/31793297-25745706-b51f-11e7-8ea4-0c69b57c496d.png)
(always used the same books: tome with sharpness 5, and …
> fix ancient tomes when using enchanted books with more than one enchantment

- src/main/java/vazkii/quark/misc/feature/AncientTomes.java
Follow up to #652 
Fixes the cost to apply a book with overlevel enchantments when it has other enchantments.
Also allows renaming an item while applying such a book
> fix ancient tomes when using enchanted books with more than one enchantment [follow up]

- src/main/java/vazkii/quark/tweaks/feature/JumpBoostStepAssist.java
1.25F is player jump height, which is what should ideally be used for step assist. This allows a player to step up to places where they would otherwise be able to jump to, such as a block with 2 layers of snow on top of it.
If there are other places in the code where this needs changing, feel free to close this PR and I'll open an issue for it to be dealt with later.
> Fix incorrect step assist height

- src/main/java/vazkii/quark/world/feature/NaturalBlazesInNether.java
Tested with Biomes O' Plenty, and I did in fact see some blazes. So that's a plus.
Also fixed a Scala Arrays import because I thought I needed a method out of the Java Arrays class, but it turns out I didn't, and even though you fix the imports when building, I decided to keep the fix here.
> Rework Blaze spawning code to allow spawning in modded Nether biomes.

- src/main/java/vazkii/quark/base/handler/DropoffHandler.java
- Removed ret, because it wasn't being used, and instead return what was
found in getDropoffItemHandler(). Fixes #780.
> Fix IDropoffManager tiles being ignored. Fixes #780.

- src/main/java/vazkii/quark/decoration/entity/EntityColoredItemFrame.java
- src/main/java/vazkii/quark/decoration/entity/EntityGlassItemFrame.java
- Overrides Entity:getPickedResult and returns the correct information.
- Fixes #790.
- Haha, sorry for misspelling the commit.
> Fix Middle Clicking on Quark's Item Frames, Fixes #790

- src/main/java/vazkii/quark/base/block/BlockQuarkWall.java
- Override the method getBlockFaceShape, just like BlockWall does, and copy and pasted the logic, fixes #841.
> Torches shouldn't be allowed on the side of walls, Fixes #841

- src/main/java/vazkii/quark/tweaks/feature/GlassShards.java
- Lowered the GlassShards event to low, because it was being called before the Vitreous Pickaxe, fixes #839.
> Lowered GlassShards event priority, fixes #839

- src/main/java/vazkii/quark/tweaks/feature/DoubleDoors.java
- Custom villager, that extended from EntityVillager, that coulnd't open doors were still getting injected 
with new ai and causing weird things to happen, fixes #921.
- Made it so that a villager can only be injected with the new ai is when it had the one being replaced.
> Check if villager is capable of opening doors, fixes #921

- src/main/java/vazkii/quark/automation/feature/PistonsMoveTEs.java
Fixes #828, a bug introduced in https://github.com/Vazkii/Quark/commit/37d54882719336ca7b976669341343314691af8b
> Don't double-set blockstates when a tile entity doesn't exist to justify the #776 fix

- src/main/java/vazkii/quark/misc/entity/EntityArrowEnder.java
This simply replicates the functionality of an Ender Pearl as was suggested in the comments (and as I saw a few days prior to that). I've honestly never actually used an ender pearl from a distance before, and it took me a few tries to get the arrow to hit the portal, but it seems to be functional properly in both directions.
I'm not sure why it included spacing changes to the header. Sorry!
> Resolve #1072: include code to allow Ender Arrows to use gateways.

- src/main/java/vazkii/quark/management/feature/StoreToChests.java
I felt there was some uncertainty about the meaning of "invert". Given the context it would seem to be most likely relating to an inversion of the functionality (sneak vs no sneak), however given its proximity to the extensive positioning options, it was unclear to me until I triple-checked in the source code exactly what it did.
It probably doesn't matter, but at least this commit message is longer even than the commit itself.
> QOL tweak: explain what "Invert button" means.

- src/main/java/vazkii/quark/base/handler/ModIntegrationHandler.java
- src/main/java/vazkii/quark/world/feature/RevampStoneGen.java
Turns out serializing stacks of unregistered items makes them air, so this didn't just break JEI but actually broke chiseling of those 4 block types, but no one actually looked at the chisel GUI itself to check that.
> Move broken Chisel IMC back to init. Actually fixes #1129

- src/main/java/vazkii/quark/tweaks/feature/DoubleDoors.java
There is an issue with my mod Locks. When a door is locked, the other can still be opened because I do not cancel the event completely, but rather deny the block use result, for which your mod doesn't account for. This small addition should fix the issue.
> Add extra condition to block right click event

- src/main/java/vazkii/quark/decoration/client/render/RenderFlatItemFrame.java
Before fix:
After fix:
(Left: Vanilla Map, Right: Modded map, extending ItemMap)
> Fixed flat item frames only extending its model, when vanilla maps were placed in it

- src/main/java/vazkii/quark/tweaks/ai/EntityAIOpenDoubleDoor.java
Currently, if a door is removed during the same tick in which the AI task is executed, the game will crash, because it can't get the `BlockDoor.FACING` property anymore. This issue does not exist in Vanilla since they perform the same check that has been added in this commit in `BlockDoor::toggleDoor` before doing anything.
Unfortunately including a repro is quite difficult because of the required timing, but for completeness I have included the stacktrace of the relevant crash below. (The stacktrace originates from a version that is likely not the latest release and definitely not `master` but the issue persits on the current `master`.)
<details>
<summary>Click to expand</summary><p>
Stacktrace:
```
java.lang.IllegalArgumentException: Cannot get property PropertyDirection{name=facing, …
```
> Fixes DoubleDoor AI crashing if the door is removed in the same tick

- build.gradle
- build.properties
- src/main/java/vazkii/quark/integration/jei/ElytraDuplicationExtension.java
- src/main/java/vazkii/quark/integration/jei/QuarkJeiPlugin.java
- src/main/java/vazkii/quark/integration/jei/package-info.java
- src/main/java/vazkii/quark/vanity/module/ColorRunesModule.java
- src/main/resources/assets/quark/lang/en_us.json
Anvil recipes supported are 
* ancient tomes + enchanted books
* runes + enchanted items, 
* repairing pickarangs.
Elytra duping doesn't show up due to a JEI bug (mezz/JustEnoughItems#1785) at the moment, so the "Makes copy" text isn't rendered yet as I can't verify the position. The position was copied from the 1.12 code.
JEI is not added to the toml as I don't think we use anything that wasn't in 6.0.
> Add JEI integration for elytra duping and anvil recipes

- build.gradle
- src/main/java/vazkii/quark/client/feature/ItemsFlashBeforeExpiring.java
- src/main/resources/quark_at.cfg
My first instinct was to actually replace this with a proper cached
reflection call, but given the number of times that this is potentially
being called on a server with a large number of players (to the point
where it is causing `EntityItem::onUpdate` to take up around 7% of tick
time), this seems like the situation that access transformers were
**explicitly designed for**.
I feel as though even cached reflection would still add additional
overhead.
Especially given that this code is injected irregardless of the setting
being enabled (it being a client-side setting), speed would seem to be a
priority here.
Relevant profile:
> Fix considerable overhead caused by uncached reflection.

- src/main/resources/data/forge/tags/blocks/chests/trapped.json
- src/main/resources/data/forge/tags/blocks/chests/wooden.json
- src/main/resources/data/forge/tags/items/chests/trapped.json
- src/main/resources/data/forge/tags/items/chests/wooden.json
- src/main/resources/data/quark/recipes/tweaks/crafting/utility/chests/compat/driftwood_chest_wood.json
- src/main/resources/data/quark/recipes/tweaks/crafting/utility/chests/compat/poise_chest_wood.json
- src/main/resources/data/quark/recipes/tweaks/crafting/utility/chests/compat/willow_chest_wood.json
- src/main/resources/data/quark/recipes/tweaks/crafting/utility/chests/compat/wisteria_chest_wood.json
This Pull Request fixes the tags so that the wooden chest tag contains new compat chests, as does the trapped chest tag. It also makes the recipes using logs to get 4 chests work for compat chests.
Fixes #1821
Fixes #1822
Fixes #1825
> Fix chest tags & recipes for newer chests

- src/main/java/vazkii/quark/tweaks/module/SignEditingModule.java
Fix sign edits not persisting if the sign is edited after the chunk it's in is reloaded. Fixes #2116. 
This fix also needs to be applied to 1.15.
> Fix broken sign editing behavior when edit occurs after chunk reload

- src/main/java/vazkii/quark/base/handler/MiscUtil.java
- src/main/resources/META-INF/accesstransformer.cfg
This change is a workaround for an issue with the access transformer entries not being applied in IntelliJ IDEA (cause unknown, although I suspect it to be related to that fact that Forge patches both fields to change their types from arrays to lists). This also fixes the implementation where it previously had a redundant null check and didn't check the collection size before getting the 0th element.
> Use method handles for loot table modification

- src/main/java/vazkii/quark/base/handler/GeneralConfig.java
Added Crafting and Pattern Terminals from AE2 to the Ignore Screen list, as the buttons don't play well with them.
> Ignore Terminals from Applied Energistics

- src/main/java/vazkii/quark/world/client/RealisticGenScreen.java
- src/main/java/vazkii/quark/world/gen/RealisticChunkGenerator.java
- src/main/java/vazkii/quark/world/gen/RealisticGenScreen.java
- src/main/java/vazkii/quark/world/module/RealisticWorldGenModule.java
- src/main/resources/META-INF/accesstransformer.cfg
- src/main/resources/assets/quark/lang/en_us.json
This PR re-implements the old realistic world type from previous quark versions. Unfortunately due to fundamental changes in the world generator, certain additions such as a larger river size and increased water lake rarity were not ported. Servers can use the realistic world type by setting the level-type value in the server.properties file to `realistic`.
> Re-implement realistic world type

- src/main/java/vazkii/quark/building/module/MoreBrickTypesModule.java
Snow Bricks were getting their properties from snow, which is the layered version, not Snow Blocks
> Change Snow Bricks properties to be from Snow Blocks; Fixes #2396

- src/main/java/vazkii/quark/base/handler/GeneralConfig.java
The Crafting Grid was not being ignored, because of a refactor in Refined Storage, with this config change it will be correctly ignored once again.
This change has been verified in-game.
> Removed Filter Buttons from RS Crafting Grid

- src/main/java/vazkii/quark/world/gen/structure/processor/BigDungeonChestProcessor.java
This code creates an inherently worldless tile entity (which can become
problematic with `fillWithLoot`), sets a null loot table (when the
default is already null), replaces the contents with empty item stacks
(when they should in theory already be null), and then sets the loot
table.
It then serializes the tile entity back to NBT and returns it.
Given that we have access to the tile entity NBT originally, it's a
simple matter of comparing the type to `minecraft:chest` and, if so,
setting the `LootTable` and `LootTableSeed` values for the NBT compound.
This commit simplifies the code to do precisely that: check for a chest,
set the relevant loot table and add a seed, and then return a new(?)
BlockInfo containing those. I'm unsure if returning the original
BlockInfo with the modified NBT …
> Simplify BigDungeonChestProcessor loot table code. (1.16)

- src/main/java/vazkii/quark/world/block/ElderPrismarineBlock.java
- src/main/java/vazkii/quark/world/module/underground/ElderPrismarineUndergroundBiomeModule.java
Closes #1574. Adds a new class, ElderPrismarineBlock, which extends QuarkBlock and returns true for isConduitFrame, and changes the elder prismarine blocks to use this class instead.
> Added conduit support for elder prismarine

- src/main/java/vazkii/quark/tools/item/SlimeInABucketItem.java
Not tested, but just something I saw while reviewing from github
Might fix #1998
> Fix coordinate typo in SlimeInABucketItem

- src/main/resources/data/minecraft/tags/blocks/climbable.json
Closes #2372. 1.16 introduced a new `#minecraft:climbable` tag that is used to recognize which blocks are climbable, and since Quark ladders were missing from the tag the game did not recognize the climbing action.
I also looked into the issue where iron ladders are making stone sounds. The custom sound type works perfectly, but it seems that the `METAL_` sound events are playing stone sounds instead. Could possibly be a Forge issue, but I don't know for sure.
> Add quark ladders to #minecraft:climbable tag

- src/main/resources/data/minecraft/tags/blocks/soul_fire_base_blocks.json
Slabs, Stairs, Vertical Slabs, and Walls were missing
> Add missing blocks to Soul Fire base blocks tag.

- src/main/java/vazkii/quark/integration/jei/ElytraDuplicationExtension.java
- src/main/java/vazkii/quark/integration/jei/QuarkJeiPlugin.java
- src/main/java/vazkii/quark/tweaks/module/DragonScalesModule.java
- src/main/java/vazkii/quark/tweaks/recipe/ElytraDuplicationRecipe.java
- src/main/resources/assets/quark/lang/en_us.json
* Fix broken transparency on shapeless icon for JEI elytra dupe so it doesn't look like this:
* Make the elytra recipe not lie about its registry name in JEI by actually storing it (and simplify the code by using SpecialRecipe). Just in case some modpack decides to override this or remove manually, I guess. It was just annoying me.
* Make the requirement of applying runes clearer by naming the items "Any Enchanted Item" because it still has the thing where looking up a recipe for one of those items shows all of them in the other slot. Fixing it would mean keeping a single item for each rune or blowing up the number of recipes, so this would at least make it clear.
> Minor tweaks to JEI integration and elytra duping

- src/main/java/vazkii/quark/base/world/generator/multichunk/ClusterBasedGenerator.java
- src/main/java/vazkii/quark/base/world/generator/multichunk/ClusterShape.java
- src/main/java/vazkii/quark/world/gen/BigStoneClusterGenerator.java
- src/main/java/vazkii/quark/world/gen/UndergroundBiomeGenerator.java
- src/main/java/vazkii/quark/world/gen/UndergroundSpaceGenerator.java
This PR does several things to try and improve the caves but it isn't perfect of course. Always room for improvement!
Some things it does:
- Tries to surround lava with the carved block to lake lava slopes looks better. This can be removed in favor of just tick updating the lava instead. (works on the majority of lava. There are some lava that is unaffected and I am not sure why. Very odd)
- changed code to not carve blocks under liquids exposed to the sky (ocean floors and rivers) so there is no biome check needed now. (vanilla lake feature towards the surface of the world could cause issues. I hate vanilla lakes lol)
- will now try to remove floating grass and speleothems and such so these kinds of stuff is much rarer. 
- pass in the difference between the target threshold and the noise …
> attempt to improving quark caves

- src/main/java/vazkii/quark/building/module/ShinglesModule.java
I noticed after creating a map for my build utilizing blue shingles they appeared orange, so I've resolved that here.
> Fix shingle map colors

- src/main/resources/assets/quark/models/block/burnt_vine_1.json
- src/main/resources/assets/quark/models/block/burnt_vine_1u.json
- src/main/resources/assets/quark/models/block/burnt_vine_2.json
- src/main/resources/assets/quark/models/block/burnt_vine_2_opposite.json
- src/main/resources/assets/quark/models/block/burnt_vine_2u.json
- src/main/resources/assets/quark/models/block/burnt_vine_2u_opposite.json
- src/main/resources/assets/quark/models/block/burnt_vine_3.json
- src/main/resources/assets/quark/models/block/burnt_vine_3u.json
- src/main/resources/assets/quark/models/block/burnt_vine_4.json
- src/main/resources/assets/quark/models/block/burnt_vine_4u.json
- src/main/resources/assets/quark/models/block/burnt_vine_u.json
- src/main/resources/assets/quark/models/block/ladder_but_not_the_vanilla_one_so_resourcepacks_dont_override_it.json
- src/main/resources/assets/quark/models/block/root_1.json
- src/main/resources/assets/quark/models/block/root_1u.json
- src/main/resources/assets/quark/models/block/root_2.json
- src/main/resources/assets/quark/models/block/root_2_opposite.json
- src/main/resources/assets/quark/models/block/root_2u.json
- src/main/resources/assets/quark/models/block/root_2u_opposite.json
- src/main/resources/assets/quark/models/block/root_3.json
- src/main/resources/assets/quark/models/block/root_3u.json
- src/main/resources/assets/quark/models/block/root_4.json
- src/main/resources/assets/quark/models/block/root_4u.json
- src/main/resources/assets/quark/models/block/root_u.json
- Fixes #2719
- Also decided to fix this for burnt vines and ladders since they were affected by the same thing
- Removed the tint index parameter from cave roots since it didn't seem to be actually doing anything and was left over from the normal vine model
> Fix several planes which were not properly mirrored from behind

- src/main/java/vazkii/quark/base/proxy/CommonProxy.java
Coming over from charm again: 
We're trying to check if quark modules are enabled in `FMLCommonSetupEvent` (to disable our modules which would do the same).
Quark currently marks its modules as enabled during that phase, which is a parallel event and leads to race conditions with our checks.
This change lets the very first `ModConfigEvent` through, which means Quarks modules are marked as enabled before `FMLCommonSetupEvent` starts.
We hope this works for you. Let me know if further discussion is necessary.
> [Compat] [Charm] Mark modules as enabled earlier

- src/main/java/vazkii/quark/base/proxy/CommonProxy.java
The change in #2754 did not have the intended effect due to an integer overflow. Change the number the be the same as the one in L69.
Sorry for wasting your time with the first PR.
> [Compat] [Charm] [Now really] Mark modules as enabled earlier

- src/main/java/vazkii/quark/base/block/QuarkPressurePlateBlock.java
- src/main/java/vazkii/quark/content/automation/block/ObsidianPressurePlateBlock.java
This cleans up the implementation for the obsidian pressure plates, allowing third parties to be indirectly aware of the `POWERED` property due to being in the hierarchy of `PressurePlateBlock`. Also just allows for removal of a lot of code already provided by Mojang's implementation. If weighted pressure plates or other entirely custom implementations are needed in the future, they can always have their own boilerplate classes.
> Inherit from pressure plate block implementation

- src/main/java/vazkii/quark/base/client/handler/InventoryButtonHandler.java
- Cancels the input events when sorting will occur, to avoid subsequent GUI listeners from affecting the state
- Fixes https://github.com/Vazkii/Quark/issues/1782
- Fixes conflict between target inventory sorting and in-world creative mode pick-block (issue predates this PR)
> Fix various inventory sorting input issues

- web/features.json
Website says Ravager Hide drop increases with Fortune, when it means Looting.
Very important please fix thanks
> Website Ravager Hide Description, Fortune ->Looting

- src/main/java/vazkii/quark/api/config/IConfigCategory.java
- src/main/java/vazkii/quark/api/config/IConfigElement.java
- src/main/java/vazkii/quark/base/client/config/ConfigCategory.java
- src/main/java/vazkii/quark/base/client/config/ConfigObject.java
- src/main/java/vazkii/quark/base/client/config/IngameConfigHandler.java
- src/main/java/vazkii/quark/base/client/config/gui/widget/QButton.java
- src/main/java/vazkii/quark/base/client/config/obj/AbstractStringInputObject.java
- src/main/java/vazkii/quark/base/client/config/obj/BooleanObject.java
- src/main/java/vazkii/quark/base/client/config/obj/DoubleObject.java
- src/main/java/vazkii/quark/base/client/config/obj/IntegerObject.java
- src/main/java/vazkii/quark/base/client/config/obj/ListObject.java
- src/main/java/vazkii/quark/base/client/config/obj/StringObject.java
- src/main/java/vazkii/quark/base/handler/GeneralConfig.java
- src/main/java/vazkii/quark/base/module/config/ConfigObjectSerializer.java
- src/main/java/vazkii/quark/base/module/config/IConfigBuilder.java
- src/main/java/vazkii/quark/base/module/config/IConfigCallback.java
- src/main/java/vazkii/quark/base/module/config/QuarkConfigBuilder.java
- src/main/java/vazkii/quark/base/proxy/ClientProxy.java
- src/main/java/vazkii/quark/content/world/config/StoneTypeConfig.java
* All writes to the config are done through the Forge config api now, so we no longer have to mess with replacing the file somehow without Forge or nightconfig trying to edit it at the same time.
* The stone config now defaults max height to 255 so that it doesn't correct from 256 to 256 every single time.
~~This better work.~~
Closes #3011, closes #3017
> An attempt at fixing configs

- src/main/java/vazkii/quark/content/world/gen/ObsidianSpikeGenerator.java
This was a request on my tracker. Unfortunately, it's not possible for me to hook into the tile entity's `setLootTable` method as the tile has no context around it allowing me to replace it with a Lootr chest.
Using the LockableLootTileEntity's `setLootTable` static method, on the other hand, provides all of the ncessary information, and is otherwise identical to the previous `setLootTable` statement. 
Actually, in theory this introduces a check to make sure that the tile entity is valid rather than simply casting -- in the very rare instance where setblockstate fails to properly create a tile entity for some reason.
> Add compatibility with Lootr for obsidian pillars.

- src/main/java/vazkii/quark/content/world/block/SpeleothemBlock.java
This PR does not change any behavior that the user can see. The block still can be placed, will break if it loses support and all that.
What this PR does is by making SpeleothemBlock override updatePostPlacement, it makes it much easier for other mods to know if the SpeleothemBlock is in a valid spot with support or if it should be replaced. For example: https://github.com/TelepathicGrunt/WorldBlender/blob/0f55409be94510c365f4773f793b78d2a2af44a3/src/main/java/com/telepathicgrunt/worldblender/entities/ItemClearingEntity.java#L84
My mod World Blender will iterate over the chaotic landscape and remove all blocks that are in invalid placements such as floating plants or flowers on non-dirt blocks. I found that Quark's Speleothems were not returning the correct state from …
> Made SpeleothemBlock easier for other mods to detect if it is in a valid spot

- src/main/java/vazkii/quark/content/tools/entity/PickarangEntity.java
Makes the pickarang compatible with mods that hook item pickup events, for example [Shulker Enchantments](https://github.com/Ephys/mc-shulker-enchantments). (The siphon enchantment used to not work for items returning on a pickarang.)
Should not alter game mechanics in standalone Quark. I've tested it alone and with the Shulker Enchantments mod.
Does not touch the code for picking up the pickarang itself, only the items on it. The pickarang is special cased to go into exactly the slot you threw it from, so I don't think it should be hookable by other mods.
> Improve pickarang compatibility

- src/main/java/vazkii/quark/addons/oddities/block/MatrixEnchantingTableBlock.java
- src/main/java/vazkii/quark/addons/oddities/tile/MatrixEnchantingTableTileEntity.java
- src/main/java/vazkii/quark/api/IEnchantmentInfluencer.java
- src/main/java/vazkii/quark/api/IModifiableEnchantmentInfluencer.java
I would like to add compatibility to my [mod](https://github.com/LogicTechCorp/Reagenchant) for Matrix Enchanting, but there currently isn't a way for an enchantment influencer to define custom enchantments. This PR fixes that by allowing enchantment influencers to modify their influenced enchantments.
> Allow enchantment influencers to modify influenced enchantments

- src/main/resources/assets/quark/models/block/leaf_carpet.json
Changes Leaf Carpets to use a custom thin model, to be less jarring and blend more so that they are more usable.
**BEFORE**
**AFTER**
> Improve Leaf Carpet model

- src/main/java/vazkii/quark/content/building/module/GoldBarsModule.java
My Diagonal Fences mod adds four new block states to fences.
When Quark copies all fence block state properties to it's gold bars block during nether fortress generation the game crashes as Quark also tries to copy the block state properties added by me, without checking if they're actually supported by gold bars.
So I added a simple check when copying properties to make sure they're valid for gold bars.
> Fix gold bars generation crash with mods adding new block states to fences

- src/main/java/vazkii/quark/addons/oddities/module/TotemOfHoldingModule.java
Just a simple fix. Also added a new info in the config that the Totem will always spawn if the player killer is himself.
> Fix for "Killing yourself doesn't spawn the Totem of Holding"

- src/main/java/vazkii/quark/addons/oddities/client/screen/BackpackInventoryScreen.java
Charm adds their buttons with a low priority forge event (this is why the fix in _init_ doesn't work) , to fix this an event with lower priority could be used, or just add the movement of the buttons to the render function. 
I opted for the latter.
> fixed charm buttons being inside the backpack inventory.

- src/main/java/vazkii/quark/content/tools/client/render/GlintRenderTypes.java
- src/main/resources/META-INF/accesstransformer.cfg
Resolves #3503. This is the only thing that prevents the missing dependency screen from showing up, luckily enough.
> Access render types through a subclass instead of ATs

- src/main/resources/data/quark/recipes/building/crafting/chests/chest_trapped.json
- src/main/resources/data/quark/recipes/building/crafting/chests/trapped_chest_revert.json
- src/main/resources/data/quark/tags/items/revertable_chests.json
- src/main/resources/data/quark/tags/items/revertable_trapped_chests.json
Adds the new blossom and azalea chests to the revertable chests tag.
Also creates a new tag and recipe for reverting trapped chests, and adds a version of the vanilla trapped chest recipe, making vanilla trapped chests craftable again!
Nya,
> More chest reversions

- src/main/java/vazkii/quark/content/building/module/LeafCarpetModule.java
Immersive Weathering Essentially adds a Leaf Carpet of its own, in the form of leaf piles.
> Update Leaf Carpet Anti-Overlap

- src/main/java/vazkii/quark/base/client/config/screen/AbstractScrollingWidgetScreen.java
If you click here, it counts as clicking the barely-visible config button, instead of the "done" button:
This PR changes footer buttons to be registered first, so they win. This incidentally also changes the tab index (you now visit the footer first when pressing Tab)
> Fix config GUI buttons taking click priority over footer buttons

- src/main/java/vazkii/quark/content/automation/client/render/QuarkPistonBlockEntityRenderer.java
- src/main/java/vazkii/quark/content/automation/module/PistonsMoveTileEntitiesModule.java
This fixes an issue with (at least) AE2 that's caused by creating a new block entity instead of loading the data into the one created by vanilla when the block state is set in the world.
This incidentally slightly changes the semantics of the IPistonCallback onPistonMovementFinished method, causing it to be called on the block entity that is in the world [after the data has been loaded into it] instead of on a fresh block entity that will be replacing the one that's in the world.
> Change pistons to not construct extra block entities

- src/main/java/vazkii/quark/content/tweaks/module/EnhancedLaddersModule.java
This removes the need for the explicit `swing()` call, and behaves better with other mods which might rely on `getCancellationResult`.
https://github.com/cc-tweaked/CC-Tweaked/issues/1433 describes the motivation in a little more detail, but effectively ComputerCraft's turtles rely on `getCancellationResult` to determine if a block has actually been placed or not. As it was previously not set, code assumed the block had not been placed.
> Set the cancellation result when placing ladders

- src/main/java/vazkii/quark/content/mobs/module/ForgottenModule.java
The current wording of the config description is wrong: it says that 1/forgottenSpwanRate skeletons will be transformed into a forgotten, but the actual value is simply forgottenSpwanRate.
> Clarify wording in forgotten spawn rate config description

- src/main/java/vazkii/quark/content/tools/module/PathfinderMapsModule.java
The Minecraft Fandom wiki has been forked to a new domain: minecraft.wiki. Learn more here: https://minecraft.wiki/w/Minecraft_Wiki:Moving_from_Fandom. This PR updates the old wiki link accordingly.
> Update Minecraft wiki link to new domain

- src/main/java/org/violetmoon/quark/content/experimental/client/screen/VariantSelectorScreen.java
- src/main/java/org/violetmoon/quark/content/experimental/config/BlockSuffixConfig.java
- src/main/java/org/violetmoon/quark/content/experimental/config/VariantsConfig.java
- src/main/java/org/violetmoon/quark/content/experimental/item/HammerItem.java
- src/main/java/org/violetmoon/quark/content/experimental/module/VariantSelectorModule.java
Brings the Variant Selector in line with 9a9850e65301973fb3c243226f333de3f4093adf. Doing this as a PR just to squash it tbh.
I fucked up one of the commit messages it refers to the wrong issue, second commit belongs to 08d8d93368352523cd9a924ae267afcc562f37d2
> Variant selector cherrypicks

- src/main/java/org/violetmoon/quark/base/handler/InventoryTransferHandler.java
Makes crafting tables and creative player inventory don't have chest buttons even if `chestButtonSlotTarget` value is low enough to allow it.
The extract from container button can dupe items in the crafting table
The chest buttons in the creative inventory are in the way most of the time
> Remove chest buttons from crafting table & creative inventory

- src/main/java/org/violetmoon/quark/content/client/module/ChestSearchingModule.java
- src/main/java/org/violetmoon/quark/content/management/module/InventorySortingModule.java
Containers that don't use the same length for rows as chests have the filter & sort chest buttons in the middle of them, things like Supplementaries sacks, TFC's vessels, donkeys with chests, etc
This also doesn't change the normal containers, like chests
> Make top buttons be in the top right on containers that doesn't use full chest rows

- src/main/java/org/violetmoon/quark/addons/oddities/module/MagnetsModule.java
> Gravisand allows for a variety of redstone components, **especially as its
> magnetic properties** have it constantly output a comparator signal of 15.
> Make gravisand react to magnets

- src/main/java/org/violetmoon/quark/content/client/module/ImprovedTooltipsModule.java
These items from Bumblezone disallows and allows a more unique combination of enchantments than normal equivalent items. Having them show in enchantment tooltip would be useful for users.
I am removing my code compat that was injecting these items into Quark's tooltip list of items before in favor of adding directly to Quark's config
https://github.com/TelepathicGrunt/Bumblezone/issues/354
> Add Bumblezone's special items to Quark's enchanting tooltip config

- src/main/resources/assets/quark/lang/en_us.json
`block.quark.cherry_vertical_slab` appears twice in `en_us.json`. This PR removes the duplicate entry.
> Remove duplicate `cherry_vertical_slab` key

- changelog.txt
- src/main/java/org/violetmoon/quark/content/tweaks/module/EnhancedLaddersModule.java
- src/main/java/org/violetmoon/quark/mixin/mixins/BlockBehaviourMixin.java
- src/main/java/org/violetmoon/quark/mixin/mixins/LadderBlockMixin.java
- src/main/resources/quark.mixins.json
Also simplifies the EnhancedLaddersModule logic a little bit w/ some mixinextras sauce.
Fixes #4843 
The problem is that in vanilla, the only way to make a ladder pop off the wall is to break the block behind it, and therefore the `canSurvive` checks in vanilla don't run if the block update came from a different direction. The fix is to run canSurvive logic when blocks above send updates, too.
Just for fun I made the ladders break off like bamboo. This required overriding `tick` from LadderBlock and I'm not sure if that's kosher. Would like some eyes on this before I accidentally introduce a ladder dupe bug
> Fix freestanding ladders not popping off when the top is broken (Fixes #4843)

- src/main/resources/data/minecraft/tags/items/boats.json
- src/main/resources/data/minecraft/tags/items/chest_boats.json
Azalea Boats and Chest Boats are missing the Minecraft boat tags.
> Fix Azalea boats missing Minecraft boat and chest boat tags.

- src/main/java/org/violetmoon/quark/content/tweaks/module/SlabsToBlocksModule.java
Fixes #4863 as well as any other cases where a slab recipe results in more or less than 6 slabs from 3 blocks
> Fix SlabsToBlocksModule finding the wrong recipe for certain slabs

- src/main/java/vazkii/quark/content/client/tooltip/AttributeTooltips.java
When try rendering some bug-item's tooltip in which doesn't have the correct AttributeModifier information, even it's not a bug from the quark, quark will crash the client and generate a crash report with this:
``` java
[Render thread/INFO] [ChunkBuilder/]: Stopping worker threads
[Render thread/ERROR] [net.minecraft.client.Minecraft/FATAL]: Reported exception thrown!
net.minecraft.ReportedException: Rendering screen
at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:903) ~[client-1.18.2-20220404.173914-srg.jar%23221!/:?]
at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1046) ~[client-1.18.2-20220404.173914-srg.jar%23221!/:?]
at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:665) ~[client-1.18.2-20220404.173914-srg.jar%23221!/:?]
at …
```
> Use a safer way to convert attribute map when parsing tooltips

- src/main/java/org/violetmoon/quark/content/client/module/UsageTickerModule.java
This PR modifies the default usage ticker behavior so it supports showing unstackable blocks by way of checking if the item extends `BlockItem`. This won't cover all blocks but it's a good start. Maybe it'd be worth considering tracking every item regardless of stackability, but I didn't want to stray too far from the current implementation.
In Vanilla, this could be useful for keeping track of how many beds are remaining in one's inventory when using them to hunt for ancient debris. Though my main use-case is for my own modpack where most blocks have a stack size of 1, causing them to (unfairly) fall through the current usage ticker checks.
> Show unstackable blocks in usage ticker

- src/main/java/org/violetmoon/quark/base/client/render/QuarkBoatRenderer.java
Fixes #5225
The transformation when `bubbleAngle != 0` was subtly different than the one for vanilla boats. This makes the code the same as vanilla boats.
> Fix quark boats flipping upside down on bubble columns.
